import { USER_DATA,USER_MAP_POSITION } from "./usergql";
import { GEOJSON_LOCAL_QUERY } from "./geojsongql";
import { GET_LAYERS_BY_ID,GET_SELECTED_LAYER_BRIEF,GET_SELECTED_FUTURE } from "./layergql";
import { CATS_AND_BRIEF } from "./briefgql";
import { GET_MAP_POSITION,GET_FEATURES } from "./mapgql";
import { GET_SELECTED_TAB,GET_DISPLAYED_LAYERS } from "./sidebargql";

export {
  USER_DATA,
  GEOJSON_LOCAL_QUERY,
  GET_LAYERS_BY_ID,
  GET_SELECTED_LAYER_BRIEF,
  CATS_AND_BRIEF,
  GET_MAP_POSITION,
  GET_FEATURES,
  GET_SELECTED_TAB,
  GET_DISPLAYED_LAYERS,
  GET_SELECTED_FUTURE,
  USER_MAP_POSITION
}